stages:
  - prep
  - build
  - publish

image: node:12

# Validate that the repository contains a package.json and extract a few values from it.
before_script:
  - source bin/validate-package-json.sh

# Validate that the package name is properly scoped to the project's root namespace.
# For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention
validate_package_scope:
  stage: prep
  script:
    - source bin/validate-package-scope.sh

# If no .npmrc if included in the repo, generate a temporary one to use during the publish step
# that is configured to publish to GitLab's NPM registry
create_npmrc:
  stage: prep
  script:
    - source bin/create-npmrc.sh
  artifacts:
    paths:
      - .npmrc

build:
  stage: build
  only:
    - branches
  script:
    - npm ci
    - npm run build

publish:
  stage: publish
  only:
    - master
    - tags
  script:
    - source bin/override-envs.sh
    - npm ci
    - npx semantic-release
